### ISSUE TITLE
Add sandbox payments support

### ISSUE THREAD

**Issue by Gagnant** [liqpay/sdk-ios#3]
It seems that, for now this feature isn't supported in iOS SDK. If it is, please figure out a way to do it.

**Comment by maksymhusar** [comment]
For Sandbox payment param should be added: 
"sandbox": "1".

For me it works.

**Comment by Gagnant** [comment]
Thanks but I was experiencing this issue about 2 years ago, so I suppose things may change since then, e.g. some server related stuff. Or I didn't set up it properly.

**Comment by maksymhusar** [comment]
I think this issue can be closed

**Comment by Gagnant** [comment]
Sure
